name: menu_weather
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  google_generative_ai: ^0.4.7
  flutter_chat_ui: ^2.6.1
  flutter_chat_types: ^3.6.2
  flutter_hooks: ^0.21.2
  flutter_chat_core: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - .env